version: 2
updates:
- package-ecosystem: pip
  directory: "/requirements"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: latest
  reviewers:
<<<<<<< HEAD
  - IvanVSmirnov
=======
  - IvanVSmirnov
>>>>>>> 90c72186d907feaeabb462238ef3d2743812bedf
