language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - docker

before_install:
  - docker build -t storeserv test/storeserv
  - docker build -t storeonce3 test/storeonce3
  - docker run storeserv --detach
  - docker run storeonce3 --detach

install:
  - pip install -r requirements/development.txt

script:
  - docker ru
  - pytest test/

notifications:
  email:
    recipients:
      - ivan.smirnov@hpe.com
    on_success: change
    on_failure: always