language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - docker

branches:
  only:
  - master
  - experimental

before_install:
  - docker build -t storeserv test/storeserv
  - docker build -t storeonce3 test/storeonce3

install:
  - pip install -r requirements/development.txt

script:
  - pytest test/test_storeonce3.py
  - pytest test/test_storeserv.py

notifications:
  email:
    recipients:
      - ivan.smirnov@hpe.com
    on_success: never
    on_failure: always